services:
  - type: web
    name: auramika-website
    runtime: node
    region: singapore
    rootDir: auramika-website-2
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
