import 'package:flutter/material.dart';
import '../../../core/constants/app_colors.dart';

// ── Vibe Category Model ───────────────────────────────────────────────────────
class VibeCategory {
  final String id;
  final String title;
  final String subtitle;
  final String descriptor; // e.g. "Pearls · Gold · Classic"
  final Color primaryColor;
  final Color accentColor;
  final IconData icon;
  final double gridHeight; // for staggered effect
  final String? imageUrl;

  const VibeCategory({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.descriptor,
    required this.primaryColor,
    required this.accentColor,
    required this.icon,
    this.gridHeight = 180,
    this.imageUrl,
  });
}

// ── Product Model ─────────────────────────────────────────────────────────────
class HomeProduct {
  final String id;
  final String brandName;
  final String productName;
  final double price;
  final String material; // 'Brass' | 'Copper'
  final String? imageUrl;
  final bool isExpressAvailable;
  final bool isWishlisted;
  final String vibe; // which vibe category it belongs to

  const HomeProduct({
    required this.id,
    required this.brandName,
    required this.productName,
    required this.price,
    required this.material,
    this.imageUrl,
    this.isExpressAvailable = true,
    this.isWishlisted = false,
    this.vibe = 'All',
  });
}

// ── Static Mock Data ──────────────────────────────────────────────────────────
abstract class HomeData {
  // ── Vibe Categories ─────────────────────────────────────────────────────
  static const List<VibeCategory> vibeCategories = [
    VibeCategory(
      id: 'old_money',
      title: 'Old Money',
      subtitle: 'Quiet Luxury',
      descriptor: 'Pearls · Gold · Classic',
      primaryColor: AppColors.forestGreen,
      accentColor: AppColors.gold,
      icon: Icons.diamond_outlined,
      gridHeight: 200,
      imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=600&q=80',
    ),
    VibeCategory(
      id: 'street_wear',
      title: 'Street Wear',
      subtitle: 'Hypebeast Energy',
      descriptor: 'Chains · Edgy · Bold',
      primaryColor: AppColors.textPrimary,
      accentColor: AppColors.terraCotta,
      icon: Icons.bolt_outlined,
      gridHeight: 160,
      imageUrl: 'https://images.unsplash.com/photo-1679973297332-cb76bf05275c?auto=format&fit=crop&w=600&q=80',
    ),
    VibeCategory(
      id: 'daily_minimalist',
      title: 'Daily Minimalist',
      subtitle: 'Office · College',
      descriptor: 'Clean · Simple · Refined',
      primaryColor: AppColors.brass,
      accentColor: AppColors.goldLight,
      icon: Icons.circle_outlined,
      gridHeight: 160,
      imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=600&q=80',
    ),
    VibeCategory(
      id: 'party_glam',
      title: 'Party / Glam',
      subtitle: 'Statement Pieces',
      descriptor: 'Stones · Sparkle · Drama',
      primaryColor: AppColors.copper,
      accentColor: AppColors.gold,
      icon: Icons.auto_awesome_outlined,
      gridHeight: 200,
      imageUrl: 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?auto=format&fit=crop&w=600&q=80',
    ),
  ];

  // ── High-End Imitation Jewelry Catalog (50 Items) ───────────────────────
  static const List<HomeProduct> allProducts = [
    // ── EARRINGS (1-15) ───────────────────────────────────────────────────
    HomeProduct(
      id: 'e1',
      brandName: 'AURAMIKA',
      productName: 'Chunky Gold Hoops',
      price: 499,
      material: 'Gold Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/e1_gold_hoops.jpg',
    ),
    HomeProduct(
      id: 'e2',
      brandName: 'AURAMIKA',
      productName: 'Crystal Drop Earrings',
      price: 899,
      material: 'Silver / Diamond',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/e2_crystal_drop.jpg',
    ),
    HomeProduct(
      id: 'e3',
      brandName: 'AURAMIKA',
      productName: 'Pearl Studs',
      price: 299,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/e3_pearl_studs.jpg',
    ),
    HomeProduct(
      id: 'e4',
      brandName: 'AURAMIKA',
      productName: 'Vintage Coin Dangelers',
      price: 649,
      material: 'Antique Gold',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/e4_coin_dangle.jpg',
    ),
    HomeProduct(
      id: 'e5',
      brandName: 'AURAMIKA',
      productName: 'Emerald Cut Solitaire Studs',
      price: 599,
      material: 'Silver / Zircon',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/e5_emerald_studs.jpg',
    ),
    HomeProduct(
      id: 'e6',
      brandName: 'AURAMIKA',
      productName: 'Rose Gold Huggies',
      price: 399,
      material: 'Rose Gold',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/e6_rose_huggies.jpg',
    ),
    HomeProduct(
      id: 'e7',
      brandName: 'AURAMIKA',
      productName: 'Oversized Geometric Hoops',
      price: 449,
      material: 'Silver Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/e7_geo_hoops.jpg',
    ),
    HomeProduct(
      id: 'e8',
      brandName: 'AURAMIKA',
      productName: 'Kundan Chandbali',
      price: 1299,
      material: 'Gold Plated',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/e8_kundan_chandbali.jpg',
    ),
    HomeProduct(
      id: 'e9',
      brandName: 'AURAMIKA',
      productName: 'Chain Link Drop',
      price: 549,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/e9_chain_drop.jpg',
    ),
    HomeProduct(
      id: 'e10',
      brandName: 'AURAMIKA',
      productName: 'Diamond Heart Studs',
      price: 349,
      material: 'Silver / Zircon',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/e10_heart_studs.jpg',
    ),
    HomeProduct(
      id: 'e11',
      brandName: 'AURAMIKA',
      productName: 'Matte Gold Statement',
      price: 799,
      material: 'Matte Gold',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/e11_matte_statement.jpg',
    ),
    HomeProduct(
      id: 'e12',
      brandName: 'AURAMIKA',
      productName: 'Silver Needle Threaders',
      price: 249,
      material: 'Silver Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/e12_silver_threaders.jpg',
    ),
    HomeProduct(
      id: 'e13',
      brandName: 'AURAMIKA',
      productName: 'Baroque Pearl Drop',
      price: 999,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/e13_baroque_pearl.jpg',
    ),
    HomeProduct(
      id: 'e14',
      brandName: 'AURAMIKA',
      productName: 'Rainbow Stone Hoops',
      price: 599,
      material: 'Gold Plated',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/e14_rainbow_hoops.jpg',
    ),
    HomeProduct(
      id: 'e15',
      brandName: 'AURAMIKA',
      productName: 'Black Enamel Studs',
      price: 399,
      material: 'Gold / Enamel',
      vibe: 'Street Wear',
      imageUrl: 'https://images.unsplash.com/photo-1716461114307-6e6bf4e75ba5?auto=format&fit=crop&w=600&q=80',
    ),


    // ── NECKLACES (16-30) ─────────────────────────────────────────────────
    HomeProduct(
      id: 'n1',
      brandName: 'AURAMIKA',
      productName: 'Herringbone Chain',
      price: 699,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/n1_herringbone.jpg',
    ),
    HomeProduct(
      id: 'n2',
      brandName: 'AURAMIKA',
      productName: 'Diamond Tennis Necklace',
      price: 1499,
      material: 'Silver / Zircon',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/n2_tennis_neck.jpg',
    ),
    HomeProduct(
      id: 'n3',
      brandName: 'AURAMIKA',
      productName: 'Layered Coin Necklace',
      price: 799,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/n3_layered_coin.jpg',
    ),
    HomeProduct(
      id: 'n4',
      brandName: 'AURAMIKA',
      productName: 'Pearl Choker',
      price: 599,
      material: 'Faux Pearl',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/n4_pearl_choker.jpg',
    ),
    HomeProduct(
      id: 'n5',
      brandName: 'AURAMIKA',
      productName: 'Initial Pendant',
      price: 399,
      material: 'Gold Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/n5_initial_pendant.jpg',
    ),
    HomeProduct(
      id: 'n6',
      brandName: 'AURAMIKA',
      productName: 'Evil Eye Charm',
      price: 449,
      material: 'Silver / Enamel',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/n6_evil_eye.jpg',
    ),
    HomeProduct(
      id: 'n7',
      brandName: 'AURAMIKA',
      productName: 'Crystal Y-Necklace',
      price: 899,
      material: 'Rose Gold',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/n7_y_necklace.jpg',
    ),
    HomeProduct(
      id: 'n8',
      brandName: 'AURAMIKA',
      productName: 'Chunky Curb Chain',
      price: 999,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/n8_curb_chain.jpg',
    ),
    HomeProduct(
      id: 'n9',
      brandName: 'AURAMIKA',
      productName: 'Snake Chain',
      price: 549,
      material: 'Silver Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/n9_snake_chain.jpg',
    ),
    HomeProduct(
      id: 'n10',
      brandName: 'AURAMIKA',
      productName: 'Emerald Stone Pendant',
      price: 699,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/n10_emerald_pendant.jpg',
    ),
    HomeProduct(
      id: 'n11',
      brandName: 'AURAMIKA',
      productName: 'Butterfly Charm Necklace',
      price: 499,
      material: 'Rose Gold',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/n11_butterfly.jpg',
    ),
    HomeProduct(
      id: 'n12',
      brandName: 'AURAMIKA',
      productName: 'Heavy Temple Necklace',
      price: 2499,
      material: 'Antique Gold',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/n12_temple_neck.jpg',
    ),
    HomeProduct(
      id: 'n13',
      brandName: 'AURAMIKA',
      productName: 'Paperclip Chain',
      price: 649,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/n13_paperclip.jpg',
    ),
    HomeProduct(
      id: 'n14',
      brandName: 'AURAMIKA',
      productName: 'Black Bead Mangalsutra',
      price: 399,
      material: 'Gold Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/n14_mangalsutra.jpg',
    ),
    HomeProduct(
      id: 'n15',
      brandName: 'AURAMIKA',
      productName: 'Zircon Statement Choker',
      price: 1999,
      material: 'Silver / Zircon',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/n15_zircon_choker.jpg',
    ),


    // ── RINGS (31-40) ─────────────────────────────────────────────────────
    HomeProduct(
      id: 'r1',
      brandName: 'AURAMIKA',
      productName: 'Signet Ring',
      price: 499,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/r1_signet.jpg',
    ),
    HomeProduct(
      id: 'r2',
      brandName: 'AURAMIKA',
      productName: 'Solitaire Ring',
      price: 599,
      material: 'Silver / Zircon',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/r2_solitaire.jpg',
    ),
    HomeProduct(
      id: 'r3',
      brandName: 'AURAMIKA',
      productName: 'Stackable Band Set',
      price: 399,
      material: 'Rose Gold',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/r3_stack_set.jpg',
    ),
    HomeProduct(
      id: 'r4',
      brandName: 'AURAMIKA',
      productName: 'Chunky Abstract Ring',
      price: 549,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/r4_abstract_ring.jpg',
    ),
    HomeProduct(
      id: 'r5',
      brandName: 'AURAMIKA',
      productName: 'Cocktail Stone Ring',
      price: 899,
      material: 'Gold / Ruby',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/r5_cocktail_ring.jpg',
    ),
    HomeProduct(
      id: 'r6',
      brandName: 'AURAMIKA',
      productName: 'Pearl Ring',
      price: 449,
      material: 'Gold / Pearl',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/r6_pearl_ring.jpg',
    ),
    HomeProduct(
      id: 'r7',
      brandName: 'AURAMIKA',
      productName: 'Serpent Ring',
      price: 499,
      material: 'Antique Silver',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/r7_serpent_ring.jpg',
    ),
    HomeProduct(
      id: 'r8',
      brandName: 'AURAMIKA',
      productName: 'Eternity Band',
      price: 699,
      material: 'Silver / Zircon',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/r8_eternity_band.jpg',
    ),
    HomeProduct(
      id: 'r9',
      brandName: 'AURAMIKA',
      productName: 'Heart Signet',
      price: 399,
      material: 'Gold Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/r9_heart_signet.jpg',
    ),
    HomeProduct(
      id: 'r10',
      brandName: 'AURAMIKA',
      productName: 'Adjustable Evil Eye',
      price: 299,
      material: 'Gold / Enamel',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/r10_adjust_eye.jpg',
    ),

    // ── BRACELETS (41-50) ─────────────────────────────────────────────────
    HomeProduct(
      id: 'b1',
      brandName: 'AURAMIKA',
      productName: 'Tennis Bracelet',
      price: 999,
      material: 'Silver / Zircon',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/b1_tennis_bracelet.jpg',
    ),
    HomeProduct(
      id: 'b2',
      brandName: 'AURAMIKA',
      productName: 'Gold Link Bracelet',
      price: 699,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/b2_gold_link.jpg',
    ),
    HomeProduct(
      id: 'b3',
      brandName: 'AURAMIKA',
      productName: 'Charm Bracelet',
      price: 799,
      material: 'Rose Gold',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/b3_charm_bracelet.jpg',
    ),
    HomeProduct(
      id: 'b4',
      brandName: 'AURAMIKA',
      productName: 'Cuff Bangle',
      price: 599,
      material: 'Gold Plated',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/b4_cuff_bangle.jpg',
    ),
    HomeProduct(
      id: 'b5',
      brandName: 'AURAMIKA',
      productName: 'Black Leather Wristband',
      price: 499,
      material: 'Leather / Silver',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/b5_leather_band.jpg',
    ),
    HomeProduct(
      id: 'b6',
      brandName: 'AURAMIKA',
      productName: 'Evil Eye Bracelet',
      price: 349,
      material: 'Silver / Enamel',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/b6_evil_eye_brace.jpg',
    ),
    HomeProduct(
      id: 'b7',
      brandName: 'AURAMIKA',
      productName: 'Pearl Bracelet',
      price: 549,
      material: 'Faux Pearl',
      vibe: 'Old Money',
      imageUrl: 'assets/images/products/b7_pearl_bracelet.jpg',
    ),
    HomeProduct(
      id: 'b8',
      brandName: 'AURAMIKA',
      productName: 'Zircon Bangles (Set)',
      price: 1499,
      material: 'Gold / Zircon',
      vibe: 'Party / Glam',
      imageUrl: 'assets/images/products/b8_zircon_bangles.jpg',
    ),
    HomeProduct(
      id: 'b9',
      brandName: 'AURAMIKA',
      productName: 'Minimalist Chain',
      price: 299,
      material: 'Silver Plated',
      vibe: 'Daily Minimalist',
      imageUrl: 'assets/images/products/b9_min_chain.jpg',
    ),
    HomeProduct(
      id: 'b10',
      brandName: 'AURAMIKA',
      productName: 'Chunky Curb Bracelet',
      price: 799,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      imageUrl: 'assets/images/products/b10_curb_brace.jpg',
    ),

    // ── STREET WEAR DROPS (sw1–sw8) ───────────────────────────────────────
    HomeProduct(
      id: 'sw1',
      brandName: 'AURAMIKA',
      productName: 'Miami Cuban Chain',
      price: 1299,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/n8_curb_chain.jpg',
    ),
    HomeProduct(
      id: 'sw2',
      brandName: 'AURAMIKA',
      productName: 'Ear Cuff Cluster Set',
      price: 599,
      material: 'Silver Plated',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/e7_geo_hoops.jpg',
    ),
    HomeProduct(
      id: 'sw3',
      brandName: 'AURAMIKA',
      productName: 'Spike Collar Choker',
      price: 699,
      material: 'Black / Silver',
      vibe: 'Street Wear',
      isExpressAvailable: false,
      imageUrl: 'assets/images/products/n15_zircon_choker.jpg',
    ),
    HomeProduct(
      id: 'sw4',
      brandName: 'AURAMIKA',
      productName: 'Armour Finger Ring Set',
      price: 849,
      material: 'Antique Silver',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/r4_abstract_ring.jpg',
    ),
    HomeProduct(
      id: 'sw5',
      brandName: 'AURAMIKA',
      productName: 'Gold Body Chain',
      price: 1099,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      isExpressAvailable: false,
      imageUrl: 'assets/images/products/n3_layered_coin.jpg',
    ),
    HomeProduct(
      id: 'sw6',
      brandName: 'AURAMIKA',
      productName: 'Chain Anklet Stack',
      price: 499,
      material: 'Gold Plated',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/b10_curb_brace.jpg',
    ),
    HomeProduct(
      id: 'sw7',
      brandName: 'AURAMIKA',
      productName: 'Gothic Cross Pendant',
      price: 449,
      material: 'Black / Gold',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/sw7_gothic_cross.jpg',
    ),
    HomeProduct(
      id: 'sw8',
      brandName: 'AURAMIKA',
      productName: 'XL Hoop Ear Weights',
      price: 349,
      material: 'Silver Plated',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/e1_gold_hoops.jpg',
    ),
  ];

  // ── Weekend Edit (Trending) ───────────────────────────────────────────────
  static final List<HomeProduct> weekendEdit = [
    HomeProduct(
      id: 'e1',
      brandName: 'AURAMIKA',
      productName: 'Chunky Gold Hoops',
      price: 499,
      material: 'Gold Plated',
      vibe: 'Daily Minimalist',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/e1_gold_hoops.jpg',
    ),
    HomeProduct(
      id: 'n2',
      brandName: 'AURAMIKA',
      productName: 'Diamond Tennis Necklace',
      price: 1499,
      material: 'Silver / Zircon',
      vibe: 'Party / Glam',
      isExpressAvailable: false,
      imageUrl: 'assets/images/products/n2_tennis_neck.jpg',
    ),
    HomeProduct(
      id: 'r1',
      brandName: 'AURAMIKA',
      productName: 'Signet Ring',
      price: 499,
      material: 'Gold Plated',
      vibe: 'Old Money',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/r1_signet.jpg',
    ),
    HomeProduct(
      id: 'b1',
      brandName: 'AURAMIKA',
      productName: 'Tennis Bracelet',
      price: 999,
      material: 'Silver / Zircon',
      vibe: 'Party / Glam',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/b1_tennis_bracelet.jpg',
    ),
    HomeProduct(
      id: 'e4',
      brandName: 'AURAMIKA',
      productName: 'Vintage Coin Dangelers',
      price: 649,
      material: 'Antique Gold',
      vibe: 'Street Wear',
      isExpressAvailable: true,
      imageUrl: 'assets/images/products/e4_coin_dangle.jpg',
    ),
  ];
}
